import os
import sqlite3
import smtplib
import streamlit as st
from email.message import EmailMessage
from typing import TypedDict, Annotated
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, END, START
from langgraph.graph.message import add_messages
from langgraph.checkpoint.sqlite import SqliteSaver 

load_dotenv()

# --- 1. Graph State ---
class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    employee_id: str
    email: str
    session_closed: bool

# --- 2. Reliable Email Tool ---
@tool
def send_email_summary(email: str, employee_id: str, summary: str):
    """Sends a summary to the user's email via TLS (Port 587)."""
    sender_email = os.getenv("SENDER_EMAIL")
    sender_password = os.getenv("SENDER_PASSWORD")

    msg = EmailMessage()
    msg.set_content(f"Employee ID: {employee_id}\n\nSummary of Chat:\n{summary}")
    msg['Subject'] = f"Chat Summary - {employee_id}"
    msg['From'] = sender_email
    msg['To'] = email

    try:
        with smtplib.SMTP('smtp.gmail.com', 587, timeout=15) as smtp:
            smtp.starttls() 
            smtp.login(sender_email, sender_password)
            smtp.send_message(msg)
        return f"SUCCESS: Summary sent to {email}."
    except Exception as e:
        return f"FAILED: {str(e)}"

# --- 3. Graph Logic ---
llm = ChatGoogleGenerativeAI(model="gemini-2.0-flash", temperature=0)
tools = [send_email_summary]
llm_with_tools = llm.bind_tools(tools)

# --- 3. Updated Graph Logic ---
def assistant(state: AgentState):
    sys_msg = SystemMessage(content=(
        f"You are a helpful AI assistant. You are talking to Employee {state['employee_id']}. "
        "Chat about any topic. If you receive a 'SIGNAL_END' message, your task is to: "
        "1. Create a detailed summary of the conversation. "
        "2. Format the summary using bullet points. "
        "3. Include key points from both the User's questions and the AI's responses. "
        "4. Use the 'send_email_summary' tool to send this formatted summary."
    ))
    return {"messages": [llm_with_tools.invoke([sys_msg] + state["messages"])]}

def tool_node(state: AgentState):
    """Overrides LLM hallucinations and ensures correct data flow."""
    last_msg = state["messages"][-1]
    results = []
    
    # Extract the real user data from the graph state
    current_email = state.get("email")
    current_emp_id = state.get("employee_id")
    
    for tool_call in last_msg.tool_calls:
        # We ensure the tool uses the real state data, not hallucinated strings
        fixed_args = tool_call["args"]
        fixed_args["email"] = current_email
        fixed_args["employee_id"] = current_emp_id
        
        # Invoke tool with the structured summary generated by the LLM
        res = send_email_summary.invoke(fixed_args)
        results.append({"role": "tool", "content": res, "tool_call_id": tool_call["id"]})
        
    return {"messages": results, "session_closed": True}

def should_continue(state: AgentState):
    if state.get("session_closed"): return END
    if state["messages"][-1].tool_calls: return "tools"
    return END

# --- 4. Build & Compile ---
builder = StateGraph(AgentState)
builder.add_node("assistant", assistant)
builder.add_node("tools", tool_node)
builder.add_edge(START, "assistant")
builder.add_conditional_edges("assistant", should_continue, {"tools": "tools", END: END})
builder.add_edge("tools", END)

db_conn = sqlite3.connect("chat_history.db", check_same_thread=False)
memory = SqliteSaver(db_conn)
graph = builder.compile(checkpointer=memory)

# --- 5. Streamlit UI ---
st.set_page_config(page_title="AI Chat Portal", page_icon="💬")

with st.sidebar:
    st.title("Login")
    emp_input = st.text_input("Employee ID (Used for retrieval)")
    email_input = st.text_input("Your Email (For summary)")
    
    if st.button("Start/Resume Session"):
        if emp_input and email_input:
            st.session_state.config = {"configurable": {"thread_id": emp_input}}
            # Initialize state with the CORRECT inputs
            graph.update_state(st.session_state.config, {
                "employee_id": emp_input, "email": email_input, "session_closed": False
            })
            st.success(f"History for {emp_input} loaded.")
        else:
            st.warning("Please fill in both fields.")

    if st.session_state.get("config"):
        st.divider()
        if st.button("🛑 Stop & Email Summary", type="primary"):
            with st.spinner("Summarizing..."):
                output = graph.invoke(
                    {"messages": [HumanMessage(content="SIGNAL_END")]},
                    st.session_state.config
                )
                # Display the tool status (Success or Error)
                status = [m.content for m in output['messages'] if m.type == 'tool'][-1]
                st.info(status)
                st.session_state.config = None 
                st.rerun()

st.title("Generic AI Assistant")

if st.session_state.get("config"):
    # Retrieve messages from SQLite based on Employee ID
    history = graph.get_state(st.session_state.config).values.get("messages", [])
    for m in history:
        if isinstance(m, HumanMessage) and m.content != "SIGNAL_END":
            with st.chat_message("user"): st.write(m.content)
        elif isinstance(m, AIMessage) and m.content:
            with st.chat_message("assistant"): st.write(m.content)

    if user_input := st.chat_input("Ask me anything..."):
        with st.chat_message("user"): st.write(user_input)
        res = graph.invoke({"messages": [HumanMessage(content=user_input)]}, st.session_state.config)
        
        if res.get("session_closed"):
            st.success("Chat finished and summary sent!")
            st.session_state.config = None
            st.rerun()
        else:
            with st.chat_message("assistant"):
                st.write(res["messages"][-1].content)
else:
    st.info("Log in with your Employee ID and Email to begin.")